# -*- coding: utf-8 -*-
"""json_to_csv.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KJbbDiWEG4Pc55ossUdx8ea5K4lBI51a
"""

import numpy as np
import pandas as pd
import requests
import bs4 as bs

df = pd.read_json("file.json")

with open("file.json","r") as file :
  for x in file.readlines():
    print(x)

request = requests.get("https://dcplatformstorageservice-prod-us-east-1.s3-accelerate.amazonaws.com/0f96f934b6c54c4991251b63bb531834_0CE41DEA648AA3890A495F94%40techacct.adobe.com/11a57bf6-7233-413f-a0e6-d1e304b3952d?X-Amz-Security-Token=FwoGZXIvYXdzEMb%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaDDYt8y5hkAbUMeBoOiLUAUM9yuUqbKzcb2F6RdViCl2TeTVrhHnSP8shXaejtON6x6tzKX5Fz%2F30F144IxM75OnZZZ8fe7JMhPpwi3xSf2rzNUsxJl8m%2F7O6U4RTZs4owErpuhZIX2Hdx9fdWPJ5IhOfVcGl%2B9USKA9SEtrOFskTu0SsAlc1SgCIR%2FAdf8kg%2ByltQ7aXi1w%2F9JQSWttgmgtfqJ2FoTpYowmr2taNoOppo5mQRVPE4SMOgmU%2FYsd3XNXDIGzbEvqWM0gettDZF2g%2FnF%2FF5%2BUxy5FiuM1oO%2FHhb%2BmkKNSy3aQGMi1TNDDoNllBzzCt4geNQHF%2FwhQtNX29XMw%2B30jwmhE9EknzYROEEkZqyZh9Ybc%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20230624T210532Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Credential=ASIAWD2N7EVPIUKZR5X5%2F20230624%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=6e4ba78873e485aea2646e286e8dc7cfc2f5fb3c4ef749767275cdcaac40cdc5")

request.status_code

text = request.text

doc = request.json()
print(doc)

list1 = []

list1 = doc["elements"]
print(list1)

print(list(list1[17].keys()).index("abc") is None)

ind = 0
count=0
list2=[]
for dic in list1 :
  if "Text" in list(dic.keys()):
      if dic["Text"][0]=="$" :
        count+=1

      list2.append(dic["Text"])
      print(ind,dic["Text"])
      ind+=1
count-=3
print(count)

print(list2[21][list2[21].find(":")+2:])
print(list2[4][list2[4].find("#")+2:])

csv_headers = ["Bussiness__City","Bussiness__Country","Bussiness__Description","Bussiness__Name","Bussiness__StreetAddress","Bussiness__Zipcode","Customer__Address__line1","Customer__Address__line2","Customer__Email","Customer__Name","Customer__PhoneNumber"\
,"Invoice__BillDetails__Name","Invoice__BillDetails__Quantity","Invoice__BillDetails__Rate","Invoice__Description","Invoice__DueDate","Invoice__IssueDate","Invoice__Number","Invoice__Tax"]

df = pd.DataFrame(columns = csv_headers)


var=list2[1].split(",")
list_com =[]
list_com.append(var[1].strip())
list_com.append(list2[2])
list_com.append(list2[8])
list_com.append(list2[0])
list_com.append(var[0].strip())
list_com.append(list2[3])
list_com.append(list2[14])
list_com.append(list2[15])
list_com.append(list2[11])
list_com.append(list2[10])
list_com.append(list2[13])
desc = list2[17] + list2[18] + list2[19]
q = 27
for i in range(count) :
  templist = []
  templist.extend(list_com)
  templist.append(list2[q])
  templist.append(list2[q+1])
  templist.append(list2[q+2])
  templist.append(desc)
  templist.append(list2[21][list2[21].find(":")+2:])
  templist.append(list2[6])
  templist.append(list2[4][list2[4].find("#")+2:])
  templist.append(list2[54])
  df.loc[len(df.index)] = templist
  #print(len(templist))
  q+=4

print(df)

df.to_csv("result_test.csv")

print(len(csv_headers))



